package delivery

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"fde-support/internal/environment"
	"fde-support/internal/manifest"
)

// GenerateDockerCompose creates a docker-compose.yaml and .env.example for production deployment.
func GenerateDockerCompose(m *manifest.SolutionManifest, env environment.ResolvedEnvironment, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	if err := copyRuntimeInputs(m, outputDir); err != nil {
		return err
	}
	if err := generateDockerfile(outputDir); err != nil {
		return err
	}

	// Write docker-compose.yaml
	compose := generateComposeContent(m, env)
	composePath := filepath.Join(outputDir, "docker-compose.yaml")
	if err := os.WriteFile(composePath, []byte(compose), 0o644); err != nil {
		return fmt.Errorf("write docker-compose.yaml: %w", err)
	}

	// Write .env.example
	envExample := generateEnvExample(m, env)
	envPath := filepath.Join(outputDir, ".env.example")
	if err := os.WriteFile(envPath, []byte(envExample), 0o644); err != nil {
		return fmt.Errorf("write .env.example: %w", err)
	}

	// Write README
	readme := generateReadme(m, env)
	readmePath := filepath.Join(outputDir, "README.md")
	if err := os.WriteFile(readmePath, []byte(readme), 0o644); err != nil {
		return fmt.Errorf("write README.md: %w", err)
	}

	return nil
}

func generateComposeContent(m *manifest.SolutionManifest, env environment.ResolvedEnvironment) string {
	lines := []string{
		"# Code generated by solution release command. DO NOT EDIT.",
		"version: \"3.8\"",
		"services:",
		"  solution-runtime:",
		"    build:",
		"      context: .",
		"      dockerfile: Dockerfile",
		"    command: [\"solution\", \"run\", \"/manifest/manifest.yaml\", \"--env\", \"" + env.EnvironmentName + "\", \"--addr\", \"0.0.0.0:8080\"]",
		"    ports:",
		"      - \"8080:8080\"",
		"    volumes:",
		"      - ./manifest.yaml:/manifest/manifest.yaml:ro",
		"      - ./data:/manifest/data:ro",
		"      - solution-traces:/manifest/.solution/traces",
		"    environment:",
	}

	sensorTokens := collectSensorTokens(m)
	for _, token := range sensorTokens {
		lines = append(lines, fmt.Sprintf("      - %s=${%s}", token, strings.TrimPrefix(token, "env:")))
	}
	modelKeyVar := "OPENAI_API_KEY"
	if env.ModelKeyRef != "" && strings.HasPrefix(env.ModelKeyRef, "env:") {
		modelKeyVar = strings.TrimPrefix(env.ModelKeyRef, "env:")
	}
	lines = append(lines, "      - "+modelKeyVar+"=${"+modelKeyVar+"}")
	lines = append(lines, "")
	lines = append(lines, "volumes:")
	lines = append(lines, "  solution-traces:")
	lines = append(lines, "")

	return strings.Join(lines, "\n")
}

func generateEnvExample(m *manifest.SolutionManifest, env environment.ResolvedEnvironment) string {
	modelKeyVar := "OPENAI_API_KEY"
	if env.ModelKeyRef != "" && strings.HasPrefix(env.ModelKeyRef, "env:") {
		modelKeyVar = strings.TrimPrefix(env.ModelKeyRef, "env:")
	}
	lines := []string{
		"# Solution-as-Code FDE Platform - Environment Variables",
		fmt.Sprintf("# Solution: %s v%s", m.Metadata.Name, m.Metadata.Version),
		fmt.Sprintf("# Environment: %s", env.EnvironmentName),
		"",
		"# Model credentials (required)",
		modelKeyVar + "=sk-...",
		"",
	}

	sensorTokens := collectSensorTokens(m)
	for _, token := range sensorTokens {
		lines = append(lines, fmt.Sprintf("# Sensor auth token for %s", token))
		lines = append(lines, fmt.Sprintf("%s=change-me", strings.TrimPrefix(token, "env:")))
		lines = append(lines, "")
	}

	lines = append(lines, "# Action credentials")
	for _, comp := range m.Components {
		if comp.Category != "action" {
			continue
		}
		for _, val := range comp.Config {
			if s, ok := val.(string); ok && strings.HasPrefix(s, "env:") {
				lines = append(lines, fmt.Sprintf("%s=change-me  # for action %s", strings.TrimPrefix(s, "env:"), comp.ID))
			}
		}
	}

	return strings.Join(lines, "\n")
}

func generateReadme(m *manifest.SolutionManifest, env environment.ResolvedEnvironment) string {
	lines := []string{
		fmt.Sprintf("# %s", m.Metadata.Name),
		"",
		fmt.Sprintf("Version: %s", m.Metadata.Version),
		fmt.Sprintf("Environment: %s", env.EnvironmentName),
		"",
		"## Deployment",
		"",
		"1. Copy `.env.example` to `.env` and fill in the required credentials.",
		"2. Run `docker-compose up -d` to start the solution runtime.",
		"3. Verify the service is running: `curl http://localhost:8080/health`",
		"",
		"## Runtime Image",
		"",
		fmt.Sprintf("This deployment expects the Docker image `solution-runtime:%s` to be available on the target host or registry before running `docker-compose up -d`.", m.Metadata.Version),
		"Build or publish that image from the platform runtime before using this deployment package.",
		"",
		"## Rebuilding",
		"",
		"After updating the manifest or data files:",
		"```bash",
		"docker-compose down",
		"docker-compose up -d",
		"```",
		"",
		"## Manifest",
		"",
		fmt.Sprintf("The solution is defined by `manifest.yaml` in the `%s` directory.", filepath.Dir(m.Path)),
		"All configuration (components, workflows, knowledge bindings, model policies) is declared in the manifest.",
		"Modify the manifest to change solution behavior without writing code.",
	}
	return strings.Join(lines, "\n")
}

func copyRuntimeInputs(m *manifest.SolutionManifest, outputDir string) error {
	if m.Path != "" {
		if err := copyFile(m.Path, filepath.Join(outputDir, "manifest.yaml")); err != nil {
			return fmt.Errorf("copy manifest.yaml: %w", err)
		}
	}
	for _, source := range m.Knowledge.Sources {
		if source.URI == "" || strings.HasPrefix(source.URI, "/") || filepath.IsAbs(source.URI) {
			continue
		}
		// Detect Windows drive letter (C:\, D:\, etc.)
		if len(source.URI) >= 2 && source.URI[1] == ':' && (source.URI[0] >= 'A' && source.URI[0] <= 'Z' || source.URI[0] >= 'a' && source.URI[0] <= 'z') {
			continue
		}
		cleanURI := filepath.Clean(source.URI)
		if cleanURI == "." || cleanURI == ".." || strings.HasPrefix(cleanURI, ".."+string(filepath.Separator)) {
			return fmt.Errorf("knowledge source %s escapes manifest directory", source.URI)
		}
		src := filepath.Join(m.BaseDir, cleanURI)
		if !containedPath(m.BaseDir, src) {
			return fmt.Errorf("knowledge source %s escapes manifest directory", source.URI)
		}
		dst := filepath.Join(outputDir, cleanURI)
		if !containedPath(outputDir, dst) {
			return fmt.Errorf("knowledge source %s escapes output directory", source.URI)
		}
		info, err := os.Stat(src)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return fmt.Errorf("stat knowledge source %s: %w", source.URI, err)
		}
		if info.IsDir() {
			continue
		}
		if err := copyFile(src, dst); err != nil {
			return fmt.Errorf("copy knowledge source %s: %w", source.URI, err)
		}
	}
	return nil
}

func containedPath(base, target string) bool {
	baseAbs, err := filepath.Abs(base)
	if err != nil {
		return false
	}
	targetAbs, err := filepath.Abs(target)
	if err != nil {
		return false
	}
	// If the target equals the base or the target is a subdirectory of base, it's contained.
	// filepath.Rel returns "." for same directory; otherwise we check it doesn't escape.
	if baseAbs == targetAbs {
		return true
	}
	// Ensure targetAbs has path separator suffix for prefix check on exact match edge cases.
	baseSep := baseAbs + string(filepath.Separator)
	if strings.HasPrefix(targetAbs, baseSep) {
		return true
	}
	rel, err := filepath.Rel(baseAbs, targetAbs)
	if err != nil {
		return false
	}
	return rel == "." || (rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator)))
}

func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	return os.WriteFile(dst, data, 0o644)
}

func collectSensorTokens(m *manifest.SolutionManifest) []string {
	seen := map[string]bool{}
	var tokens []string
	for _, sensor := range m.Perception.Sensors {
		if ref, ok := sensor.Config["authTokenRef"].(string); ok && strings.HasPrefix(ref, "env:") {
			if !seen[ref] {
				seen[ref] = true
				tokens = append(tokens, ref)
			}
		}
	}
	return tokens
}

func generateDockerfile(outputDir string) error {
	dockerfile := `FROM golang:1.21 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o solution ./cmd/solution

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/solution /usr/local/bin/solution
ENTRYPOINT ["solution"]
`
	return os.WriteFile(filepath.Join(outputDir, "Dockerfile"), []byte(dockerfile), 0o644)
}
